# Default values for ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is adjustable without issues
replicaCount: 1

image:
  repository: 'objectrocket/sensu-operator'
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecret:
  name: 'or-docker-secret'

resourceSettings:
  limit:
    - name: cpu
      value: 500m
    - name: memory
      value: 256Mi
  request:
    - name: cpu
      value: 500m
    - name: memory
      value: 256Mi

logLevel: info

nodeSelector:
  node-role.kubernetes.io/platform_worker: "true"

tolerations:
  - effect: NoSchedule
    key: node_role
    operator: Equal
    value: platform_worker

rbac:
  clusterRole: sensu-operator

sensu:
  logLevel: info
   # To act for resources in all namespaces. More information in doc/clusterwide.md
  clusterWide: true
  # GC interval
  gcInterval: 10m
  # How often to refresh/resync all Custom Resources
  resyncInterval: 5m
  # Number of worker threads to use for processing events
  workerThreads: 4
  # Number of times to retry processing an event before giving up
  processingRetries: 5

prometheus:
  enabled: true
