apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sensu-agent
spec:
  template:
    metadata:
      labels:
        name: sensu-agent
    spec:
      containers:
        - name: sensu-agent
          image: sensu/sensu:5.1.0
          command: ["/opt/sensu/bin/sensu-agent", "start", "--id", "$(MY_NODE_NAME)", "--subscriptions", "$(MY_NODE_NAME),k8s-node"]
          env:
            - name: SENSU_BACKEND_URL
              value: ws://example-sensu-cluster-agent.default.svc.cluster.local:8081
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
