apiVersion: "sensu.io/v1beta1"
kind: "SensuCluster"
metadata:
  name: "example-sensu-cluster"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   sensu.io/scope: clusterwide
spec:
  size: 1
  version: "master"
